services:

  auth-service:
    container_name: Auth-Service
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      auth-service-db:
        condition: service_healthy
      auth-service-redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/auth-service-db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      REDIS_HOST: auth-service-redis
      REDIS_PORT: 6379

#  auth-service-db:
#    image: postgres:17-alpine
#    container_name: Auth-Service-DB
#    environment:
#      POSTGRES_DB: auth-service-db
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5438:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U username -d auth-service-db" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    volumes:
#      - auth-service-db-data:/var/lib/postgresql/data
#
#  auth-service-redis:
#    image: redis:alpine
#    container_name: Auth-Service-Redis
#    ports:
#      - "6383:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    volumes:
#      - auth-service-redis-data:/data

#volumes:
#  auth-service-db-data:
#  auth-service-redis-data:
