server:
  port: 0

application:
  keycloak:
    serverUrl: ${KEYCLOAK_URL:http://localhost:8080}
    realmUrl: ${application.keycloak.serverUrl}/realms/${application.keycloak.realm}
    tokenUrl: ${application.keycloak.realmUrl}/protocol/openid-connect/token
    realm: ecommerce-platform-project-realm
    clientId: ecommerce-platform-project-realm
    clientSecret:
    adminUsername: admin
    adminPassword: admin
    adminClientId: admin-cli


spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
    consumer:
      properties:
        spring.json.trusted.packages: "ru.ivanov.ecommerceplatformproject.sharedlibs.event*"

#jwt:
#  issuer: auth-service
#  access:
#    secret: 5ba1791dedb87fec844cd4c57bcf5c3afeb0379f4b67347a438bc559b429a52c
#    ttl: 10s
#  refresh:
#    secret: 4cfa6d5afcaef760b96163d923c05a4d7c85957acbca06649d28b21576859f1c
#    ttl: 1d
#  service:
#    secret: 057f34884f6434c80285a39344a5a47dfd3a571a0ca3e8a65768e76ffc6bb660
#    ttl: 1m

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/