server:
  port: 0

keycloak:
  serverUrl: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realmUrl: ${keycloak.serverUrl}/realms/${keycloak.realm}
  tokenUrl: ${keycloak.realmUrl}/protocol/openid-connect/token
  realm: ecommerce-platform-project
  clientId: auth-service
  clientSecret: FHrfZVMlJR1uaOxK0KdQrHJ6AhOtBag4


spring:
  application:
    name: auth-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:39092,localhost:49092}
    producer:
      acks: all
    consumer:
      properties:
        spring.json.trusted.packages: "ru.ivanov.ecommerceplatformproject.sharedlibs.event"

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

kafka:
  topics:
    user-registered: ${KAFKA_USER_REGISTERED_TOPIC_NAME:user-registered-event-topic}
    verification-code-issued: ${KAFKA_VERIFICATION_CODE_ISSUED_TOPIC_NAME:verification-code-issued-event-topic}